<a href="https://colab.research.google.com/github/Ernozkn/NUMPY-UYGULAMA-ERENOZKAN/blob/main/NUMPY_UYGULAMA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
!pip install numpy

import numpy as np
print(np.__version__)


2.0.2


**✅ 1. NumPy Getting Started**
> Açıklama: NumPy kütüphanesini np takma adıyla projeye dahil eder.






In [7]:
# 1 den 10 a kadar olan sayılar
dizi = np.array([1,2,3,4,5,6,7,8,9])
print(dizi)

[1 2 3 4 5 6 7 8 9]


**✅ 2. NumPy Creating Arrays**
> Açıklama: Verilen listedeki elemanlarla bir NumPy dizisi oluşturur.

In [8]:
# 5 elemanlı sıfırlardan oluşan bir dizi
dizi1 = np.zeros(5)
print(dizi1)

# 3x3'lük birler matrisi
dizi2 = np.ones((3, 3))
print(dizi2)

# 10 ile 20 arasında artan bir dizi
dizi3 = np.arange(10, 21)
print(dizi3)

[0. 0. 0. 0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[10 11 12 13 14 15 16 17 18 19 20]


**✅ 3. NumPy Array Indexing**
> Açıklama: arr isimli 2 boyutlu dizide 2. satırın 3. sütunundaki elemana erişir.

In [9]:
arr = np.array([[5, 10, 15],
                [20, 25, 30],
                [35, 40, 45]])
eleman = arr[1][2]
print(eleman)

30


**✅ 4. NumPy Array Slicing**
> Açıklama: Tüm satırlardan ilk iki sütunu seçer (slicing).

In [10]:
arr = np.array([[5, 10, 15],
                [20, 25, 30],
                [35, 40, 45]])
alt_dizi = arr[:, 0:2]
print(alt_dizi)

[[ 5 10]
 [20 25]
 [35 40]]


**✅ 5. NumPy Data Types**
>  Açıklama: Bir NumPy dizisinin veri tipini verir.

In [11]:
print(arr.dtype)
# Diziyi float türüne dönüştür
arr_float = arr.astype(float)
print(arr_float.dtype)

int64
float64


**✅ 6. NumPy Copy vs View**
>  Açıklama: copy() fonksiyonu orijinal dizinin bağımsız bir kopyasını oluşturur.

In [12]:
# Orijinal dizi
arr = np.array([10, 20, 30, 40])

# Kopya oluştur
arr_copy = arr.copy()

# View (görünüm) oluştur
arr_view = arr.view()

# Kopyada değişiklik yap
arr_copy[0] = 999

# View'da değişiklik yap
arr_view[1] = 888

# Hepsini yazdır
print("Orijinal dizi:", arr)
print("Kopya dizi:", arr_copy)
print("View dizi:", arr_view)

Orijinal dizi: [ 10 888  30  40]
Kopya dizi: [999  20  30  40]
View dizi: [ 10 888  30  40]


**✅ 7. NumPy Array Shape**
>  Açıklama: Dizinin satır ve sütun sayısını verir (şeklini gösterir).

In [13]:
# 3x4 boyutunda bir NumPy dizisi oluştur
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

# Dizi boyutlarını yazdır
print("Dizinin boyutları:", arr.shape)

Dizinin boyutları: (3, 4)


**✅ 8. NumPy Array Reshape**
>  Açıklama: Tek boyutlu bir diziyi 3 satır 4 sütunlu matrise dönüştürür

In [14]:
# 1'den 12'ye kadar olan sayılardan oluşan dizi oluştur (1 dahil, 13 hariç)
arr = np.arange(1, 13)

# 3x4 boyutunda matrise dönüştür
matrix = arr.reshape(3, 4)

# Matrisi yazdır
print("3x4 Matris:\n", matrix)

3x4 Matris:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


**✅ 9. NumPy Array Iterating**
>  Açıklama: NumPy dizisi üzerinde döngü kurarak satırları yazdırır

In [15]:
# 2 boyutlu NumPy dizisi
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# Satır satır döngü
for row in arr:
    for elem in row:
        print(elem, end=' ')
    print()  # Satır sonu için boş print

1 2 3 
4 5 6 
7 8 9 


**✅ 10. NumPy Array Join**
>  Açıklama: İki diziyi dikey olarak birleştirir

In [16]:
a = np.array([[1, 2],[3, 4]])

b = np.array([[5, 6],[7, 8]])
birleştirme = np.concatenate((a, b), axis=0)
print("Dikey birleştirme:\n", birleştirme)

Dikey birleştirme:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]


**✅ 11. NumPy Array Split**
>  Açıklama: Diziyi 3 parçaya böler.

In [17]:
# 1'den 12'ye kadar olan dizi (1 dahil, 13 hariç)
arr = np.arange(1, 13)

# 3 eşit parçaya böl
bölme = np.split(arr, 3)

print("3 eşit parçaya bölünmüş dizi:",bölme)

3 eşit parçaya bölünmüş dizi: [array([1, 2, 3, 4]), array([5, 6, 7, 8]), array([ 9, 10, 11, 12])]


**✅ 12. NumPy Array Search**
>  Açıklama: 25 değerinin dizideki konumunu (indeksini) verir.Açıklama: Diziyi 3 parçaya böler.

In [18]:
arr = np.array([10, 15, 20, 25, 30])
# 25 in indeks değerini buldurur
bulma = np.where(arr == 25)
print("Aranan elemanın indeks numarası:",bulma)

Aranan elemanın indeks numarası: (array([3]),)


**✅ 13. NumPy Array Sort**
>  Açıklama: Dizinin elemanlarını sıralar.

In [19]:
arr = np.array([42, 17, 8, 99, 23])
# Sayıları küçükten büyüğe sıralar
sıralı_dizi = np.sort(arr)
print("Sıralı dizi:", sıralı_dizi)

Sıralı dizi: [ 8 17 23 42 99]


**✅ 14. NumPy Array Filter**
>  Açıklama: Yalnızca çift sayıları filtreleyerek yeni bir dizi oluşturur.

In [20]:
arr = np.array([1, 2, 3, 4, 5, 6])
# çift sayıları bulur
cift_sayılar = arr[arr % 2 == 0]
print("Çift sayılar:", cift_sayılar)

Çift sayılar: [2 4 6]
